Added List method to Property package [#10]
42dx/edgio-go-sdk pull request #33
Opened 2024-03-07 22:03 UTC by rafapaulin

This method allows listing all properties under a given organization

Closes #10

2024-03-09 01:52 UTC, rafaelassumpcao requested changes

2024-03-09 01:52 UTC, rafaelassumpcao commented on internal/client/client.go
> +		}
I would remove this if/else by earlier returning the client with the user provided token, we should avoid nesting for readability purposes IMO

```go
func New(creds common.Creds, config common.ClientConfig) (Client, error) {

	credentials, err := evalCreds(creds)
	if err != nil {
		return Client{}, err
	}

	configurations, err := evalConfig(config)
	if err != nil {
		return Client{}, err
	}

	if config.AccessToken == "" {
		return Client{
			AccessToken: config.AccessToken,
			Config:      configurations,
		}, nil
	}

	accessToken, err := token.GetAccessToken(credentials)
	if err != nil {
		return Client{}, err
	}

	return Client{
		AccessToken: accessToken,
		Config:      configurations,
	}, nil

}
```

2024-03-09 01:52 UTC, rafaelassumpcao commented on internal/client/client.go
> +
this could be eliminated, see my comment down below

2024-03-09 01:52 UTC, rafaelassumpcao commented on internal/token/get-access-token.go
>  func GetAccessToken(credentials common.Creds) (string, error) {
Do we really need to call this GetAccessToken? could not be only Retrieve, so the caller code could be

```go
token.Retrieve(creds)
```

2024-03-09 01:52 UTC, rafaelassumpcao commented on internal/token/get-access-token.go
> +	fmt.Println("CalledGetAccessToken")
I know we are starting small, but I really think we should have some sort of structured logs and have the ability to log differente verbosity on these logs depending on the config or env var passed. something similar of what terraform cli does. I think they are using glog, not sure

2024-03-09 01:52 UTC, rafaelassumpcao commented on internal/utils/http.go
> +func GetHTTPJSONResult(httpClient *http.Client, request *http.Request, token string, model interface{}) error {
same idea of the other comment I did, I think we can improve on the naming here. but in this case I think we should refactor the code

- what's the purpose of having a function called GetHTTPJSONResult that does not return a result?
- this function is only returning an error or nil !?!?

2024-03-09 01:52 UTC, rafaelassumpcao commented on org/org.go
> +	Client client.Client
Hey isn't better to embed the type directly here?  or this was intentional by design?

```go
type ClientStruct struct {
    *client.Client
}
```
so you can call any methods defined on Client directly
e.g
```go
var c ClientStruct
c.CallingAnEmbededClientTypeMethod()
```

2024-03-11 18:14 UTC, rafapaulin commented
@all-contributors please add @rafaelassumpcao for review.

2024-03-11 18:17 UTC, rafapaulin commented on internal/token/get-access-token.go
>  func GetAccessToken(credentials common.Creds) (string, error) {
Changed as requested.

2024-03-11 18:18 UTC, rafapaulin commented on internal/token/get-access-token.go
> +	fmt.Println("CalledGetAccessToken")
this was a leftover from my debugging. already removed :)

2024-03-11 18:32 UTC, rafapaulin commented on internal/client/client.go
> +		}
your sample is not implemented correctly, but I got your idea, and adjusted accordingly :)

2024-03-11 18:40 UTC, rafapaulin commented on org/org.go
> +	Client client.Client
Good call, done as requested

2024-03-11 19:29 UTC, rafaelassumpcao commented on internal/client/client.go
> +		}
actually yes, my sample was incorrect because `config.AccessToken == ""` should be `config.AccessToken != ""` but your new implementation keeps nesting an if checking, would not be better to remove the top atribution and just make sure if AccessToken were provided by the user you early return it? if not you just Retrieve it and returns the client, checking for errors during the retrieve on the same level as other parts of the code?

2024-03-11 19:36 UTC, rafapaulin commented on internal/client/client.go
> +		}
If I do that I'd need 2 similar returns... One for a provided `accessToken` (returning the Client with the provided access token), and one when `accesToken` is not provided, and then is `token.Retrieve`'d. The way I did, I return just once, with the correct value.

2024-03-11 19:44 UTC, rafapaulin commented on internal/client/client.go
> +		}
But I got your point. Thinking about more complex cases, your patters would probably be more maintainable.

changed as requested :)

2024-03-11 19:45 UTC, rafaelassumpcao commented on internal/client/client.go
> +	if config.AccessToken == "" {
isn't better to change this back to `!=` helping avoiding the if nested check for errors during the retrieve?

2024-03-11 19:45 UTC, rafaelassumpcao commented on internal/client/client.go
> +	accessToken := config.AccessToken
this would be eliminated from here and directly added when needed. see comment below

2024-03-11 19:45 UTC, rafaelassumpcao commented on internal/client/client.go
> +		}
you can move you to outside this if if you invert the logic

2024-03-11 19:45 UTC, rafaelassumpcao commented on internal/utils/http.go
> +func GetHTTPJSONResult(httpClient *http.Client, request *http.Request, token string, model interface{}) error {
oh got it. thanks for clarifying I indeed didn't realized it

2024-03-11 19:45 UTC, rafaelassumpcao commented on internal/utils/to-query-string.go
nice aproach on the queryParams using set

2024-03-11 19:50 UTC, rafaelassumpcao approved these changes

2024-03-11 20:06 UTC, merged