[FEATURE] Env Var - Get All (List)
42dx/edgio-go-sdk pull request #38
Opened 2024-03-14 16:08 UTC by rafapaulin

# Proposed Changes

Add a List method to the Variables package, to list all environment variables from a given environment.

## Contribution type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update/improvement

## Related Issue(s)

- Closes #20 

## Motivation, Context and Extra Info

Having a method that abstracts most of the configuration needed makes it simple to get the environment variables from an environment, which can have its ID provided to the List environment method as a method parameter.

## Checks

### General

- [ ] I have read the org's [CONTRIBUTING](https://github.com/42dx/.github/blob/main/CONTRIBUTING.md) file
- [ ] All my commit messages follow [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/) standards (remember: we use them to auto-generate the CHANGELOG file :sweat_smile:)
- [ ] I confirmed that there aren't any other open PR about the same issue

### Code Standards

- [ ] I have performed a self-review of my own code
- [ ] Code Lint pass locally with my changes
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas

### Documentation and reliability

- [ ] My branch is up to date with the project's base branch
- [ ] I have made corresponding changes to the documentation
- [ ] The documentation changes follow the repository's docs standards
- [ ] My changes generate no new warnings

### Testing

- [ ] Existing automated tests pass locally with my changes
- [ ] I have added new unit/integration tests that prove my fix is effective or that my feature works

## How to verify the changes

1. Running the main.go file should list properties and their respective environments

## Screenshots (if appropriate)

2024-03-14 16:43 UTC, rafaelassumpcao requested changes

2024-03-14 16:43 UTC, rafaelassumpcao commented on env/list.go
> +var EnvListResult = ListResultType{}
do you really need this here?

I think you can make use of the zero value and just declare the var EnvlistResult, instead of instantiate it.

however this could be not even needed, since code below is not using this value execept to return it. so you could easily use the ListResultType{} on the return itself.

IMO this is an unnecessary attribution

2024-03-14 16:43 UTC, rafaelassumpcao commented on env/list.go
> +	err = utils.GetHTTPJSONResult(httpClient, request, c.AccessToken, &EnvListResult)
this is what I was referring to, unless you are doing nothing with the &EnvListResult, this could be replaced by the new instance itself

2024-03-14 16:43 UTC, rafaelassumpcao commented on env/list.go
> +	return EnvListResult, nil
this is what I was referring to, unless you are doing nothing with the &EnvListResult, this could be replaced by the new instance itself

2024-03-14 16:43 UTC, rafaelassumpcao commented on variable/list.go
> +var VariableListResult = ListResultType{}
do you really need this here?

I think you can make use of the zero value and just declare the var EnvlistResult, instead of instantiate it.

however this could be not even needed, since code below is not using this value execept to return it. so you could easily use the ListResultType{} on the return itself.

IMO this is an unnecessary attribution

2024-03-14 16:47 UTC, rafapaulin commented on env/list.go
> +var EnvListResult = ListResultType{}
Not sure if that is an opinion thing. Like, I need a variable, because the `GetJSONResult` method does not return anything. Instead it attributes the value it gets from the JSON unsmarshling to the `var` we pass to it as `model`. Typing the variable ensures that it maps the JSON keys to the struct correctly.

2024-03-14 16:47 UTC, rafapaulin commented on env/list.go
> +	err = utils.GetHTTPJSONResult(httpClient, request, c.AccessToken, &EnvListResult)
Nope, It needs a variable here, not a type.

2024-03-15 09:28 UTC, rafaelassumpcao approved these changes
LGTM

2024-03-15 14:28 UTC, rafaelassumpcao approved these changes

2024-03-15 14:29 UTC, merged